### PR TITLE
Fix regression after este changes and should fix #29

### LINKED ISSUE #29: este-cli feature [name] creates wrong <Route/>?
First, perhaps this should describe everything it does? It touches/creates a lot of stuff.
```shell
$ este-cli feature profile
[12:15:56] [conflict] Creating src/client/pages/profile.react.js
[12:15:56] [conflict] Creating src/client/profile/store.js
Task finished successfully
```
The route created in src/client/routes.js has different attributes than what comes in este:
```
    <Route name={Profile} path="profile" />
```
Where the other routes look like:
```
    <Route handler={Todos} name="todos"/>
```
Which results in an err (the link/menu item become visible when user is authenticated):
client/auth/login.react onFormSubmit response Error: Invariant Violation: Cannot find a route named "profile"

### PR DESCRIPTION
**Pull request by AugustinLF**

### CODE REVIEW

**Comment by grabbou** [comment]
Thank you very much! I'll review your changes later today and try to merge it! Anyway, looking briefly it looks good.

**Comment by AugustinLF** [comment]
I can also work on [#33](https://github.com/este/este-cli/issues/33), but I'd appreciate your input on that, since your file API doesn't seem to be sufficient. You can talk to me on the gitter if needed

**Comment by grabbou** [comment]
All righty, thanks a lot for your input. Please give me one more day as I am preparing for my talk at React Europe tomorrow. After all goes well, will get back to you. The CLI needs some loving and I'd definitely love to investigate Atom stuff (I am using it all the time, so nice plugin much appreciated)

**Comment by AugustinLF** [comment]
No problem, I'll be there too, so it's unlikely that I'll work on it during this time ;)

**Comment by grabbou** [comment]
Let's talk tomorrow about the `API being not sufficient`. One of the most powerful features of the CLI was the brand new rethinked file system layer (inspired by Ember), maybe there's some workaround we can implement.

**Comment by AugustinLF** [comment]
Sounds like a deal!

**Pull request merged**
